server:
  port: 8080
orchestrator:
  pipelines:
    - name: simulator-to-server-pipeline
      description: "This pipeline uses an LDES client to read an existing LDES and send the members as N-Quads to a LDES Server"
      input:
        name: be.vlaanderen.informatievlaanderen.ldes.ldi.client.LdioLdesClient
        config:
          url: http://localhost:8080/sample/by-page
        # TODO: remove this TEMP workaround (adapter | name)
        adapter:
          name: be.vlaanderen.informatievlaanderen.ldes.ldi.RdfAdapter
      outputs:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioConsoleOut
          config:
            content-type: application/n-quads

